# Generated by Django 4.2.20 on 2026-05-05 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Track', max_length=80)),
                ('author_name', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('track_data', models.JSONField()),
                ('thumbnail', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('is_template', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('owner_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remix_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='tracks.track')),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['is_public', '-updated_at'], name='tracks_trac_is_publ_b1ab4a_idx'), models.Index(fields=['is_template', '-updated_at'], name='tracks_trac_is_temp_5eeadd_idx'), models.Index(fields=['owner_token', '-updated_at'], name='tracks_trac_owner_t_85b206_idx')],
            },
        ),
    ]
